### ISSUE TITLE
Voltage of X/Y/Z motors is set too high

### ISSUE THREAD

**Issue by tankanickel** [TeamGloomy/Troodon-V2#2]
Out of the box, the voltage for the x/y/z drivers is set to 1800. This is close to the cap, that is supported and the motors might get too hot during a longer print. (Config.g, line 44)
Lowering the value to 1500 is a good starting point. Depending on the used speeds and other factors, you might want to increase this value.

**Comment by jaysuk** [comment]
for reference, this are the spec sheets for the X, Y and Z motors 
![image](https://user-images.githubusercontent.com/2574598/218460619-d3c09715-daea-452a-85b3-5f2fa3e115f8.png)

**Comment by jaysuk** [comment]
improved config sets the default current to 1600ma (80% of max)
