### ISSUE TITLE
Z-Offset is wrong when starting a new print after turning off motors

### ISSUE THREAD

**Issue by tankanickel** [TeamGloomy/Troodon-V2#5]
When the motors are turned off, either by a print g-code, manually or by a timeout, the gantry drops a bit thus invalidating a previous G32 calibration -> any new print will probably print in the air.

Solution: Run a G32 calibration either before a print in the start g-code or manually.

**Comment by jaysuk** [comment]
improved config has start_print that runs gantry levelling etc
