### ISSUE TITLE
I broke my config and didn´t backup the stock configuration (stock config included)

### ISSUE THREAD

**Issue by tankanickel** [TeamGloomy/Troodon-V2#6]
In case you somehow deleted your configuration or broke it in any other way, here´s an upload of the stock configuration. (only config, no firmware)

[Stock_Config.zip](https://github.com/TeamGloomy/Troodon-V2/files/10772845/Stock_Config.zip)

If you want to change the bed.txt and everything else to use the native firmware, like described in https://teamgloomy.github.io/troodon_v2_firmware_adjustment.html , then it is this archive. 
[Native_Firmware.zip](https://github.com/TeamGloomy/Troodon-V2/files/10772846/Native_Firmware.zip) (the firmware folder is representing the folder created after flashing the native firmware to the board)

After flashing the new firmware, the following firmware.cur file is placed on the root of the sd card.
[FIRMWARE.zip](https://github.com/TeamGloomy/Troodon-V2/files/10772898/FIRMWARE.zip)

I accidentally deleted the menu files (thanks to no confirmation screen on right click delete....) and now I use the screen menu from https://github.com/jadonmmiller/UltimateDuetMenuSystem/releases

**Comment by jaysuk** [comment]
we now have a branch for the stock profile
