### ISSUE TITLE
WiFi Module does not work (M122 reporting WiFi is disabled)

### ISSUE THREAD

**Issue by tankanickel** [TeamGloomy/Troodon-V2#8]
If QC fails, the firmware for the ESP32 WiFi module is not flashed thus rendering any wireless connectivity unusable.

To fix this issue, you need to run "M997 S1" either through Pronterface or by Putty while being connected via usb. (a .gcode file should work aswell)

**Comment by jaysuk** [comment]
covered here https://teamgloomy.github.io/troodon_v2_connected_wifi_esp32.html#wifi-issues
