### ISSUE TITLE
Description as shown in PrusaSlicer wrong, also shows as v1 with v1 bed sizes

### ISSUE THREAD

**Issue by MKHTexas** [TeamGloomy/Troodon-V2#9]
Config screen shows 4 flavors of v1, and .1mm nozzle.
In the slicer profile itself, it has 310x310x400 vs. 350x350x330
And are the speed limits real/safe limits without shaping/mods?

**Comment by jaysuk** [comment]
I'm not sure where you're seeing this.
I've just reset my slicer and reimported the config_bundle and it shows correct for me
![image](https://user-images.githubusercontent.com/2574598/226888059-87a746c0-0f58-4b27-a29b-d10f0a968772.png)

**Comment by MKHTexas** [comment]
I’m sure it is a wetware issue. I have yet to see what I would call proper “work instructions” on how to do this in PrusaSlicer. When I write them at work (I am a manufacturing engineer), I like to find a reasonably intelligent person with no prior knowledge and see if they can follow them. In the 3DP world I find that most of the time the givers of advice or instructions assume way too much about the user’s knowledge. All I know is import the bundle, then the below magically appeared. Or maybe had done something before the 2.0 profile came out and I cannot remember the magic button for this.

As a side note, I would be more than happy to be a test dummy for instructions/instruction writing. Is the below what I should be seeing at the start of the process after importing the bundle?
***@***.***

**Comment by jaysuk** [comment]
there's already instructions on how to use PrusaSlicer on their website. no point reinventing the wheel...
https://help.prusa3d.com/article/how-to-import-and-export-custom-profiles-in-prusaslicer_382766

**Comment by MKHTexas** [comment]
But is my image what I should see?

**Comment by jaysuk** [comment]
there were no images in your response so hard to tell

**Comment by MKHTexas** [comment]
IT was in my earlier email, here below:
***@***.***

**Comment by jaysuk** [comment]
still no images

![image](https://user-images.githubusercontent.com/2574598/226941644-7e9077c4-09ec-4e00-9a3a-12b0efee57d3.png)

**Comment by MKHTexas** [comment]
I’ve done it as an attachment this time, but I snipped the email it was first in so you can see that there may be a problem with images on one of our ends.

**Comment by jaysuk** [comment]
theres still no image attached. best use the github interface to load stuff

**Comment by MKHTexas** [comment]
[image to Gloomy.docx](https://github.com/TeamGloomy/Troodon-V2/files/11041701/image.to.Gloomy.docx)

**Comment by jaysuk** [comment]
no idea where that has come from. its definitely nothing to do with this release though.
Also, the slicer profile doesn't show it the configuration wizard like that.
Therefore I'll close this issue

**Comment by MKHTexas** [comment]
I went through baby steps after deleting everything on my PC with "Prusa" in it and reinstalled Alpha-5, then followed the instructions to import the bundle. I am not saying this is an issue with your s/w, I just don't live and breathe slicers and printers and even after finding everything resembling instructions I am not getting success.
![image](https://user-images.githubusercontent.com/128416032/226981839-61a33949-58d3-4a48-9268-6b36356d6242.png)

**Comment by jaysuk** [comment]
Thats the same version i'm using here and it works fine for me.
Maybe check how you downloaded the file and if in doubt, download the whole config https://github.com/TeamGloomy/Troodon-V2/archive/refs/heads/improved.zip

**Comment by MKHTexas** [comment]
When I looked at the team gloomy page, I did not see an option for the .zip. I did not see a download button for what I found, I had to right click and save as. I had no idea that we need to look in .../archive/refs/heads/improved.zip. Not intuitive. But I used the file you gave me. The .ini is hiding out in a subfolder that I could find using File Explorer, but when I look for it in Prusa to import it, it does not show. 
![image](https://user-images.githubusercontent.com/128416032/226988945-5e3c316b-1429-4b03-961a-3bf608660ec7.png)
If I can figure out the workflow I will post something on the corexy page for others, I'm probably becoming a headache but giving up is almost as hard for me as beating my head against the wall is.

**Comment by jaysuk** [comment]
![image](https://user-images.githubusercontent.com/2574598/226995200-d30ff22b-4740-483e-a332-8269a4d31b82.png)
import config from bundle
![image](https://user-images.githubusercontent.com/2574598/226995489-06a6ebb6-5854-4d19-b788-2bc9232bde85.png)
make sure you extract the zip

**Comment by MKHTexas** [comment]
Thanks for your patience, and sharp eye. 5 presets loaded. Since I have not turned my machines on yet, do I have to worry about "recalibrate your AutoZ and Toolhead Probes" since I never calibrated them? Is the config-override.g in firmware or something? Searching my hard drives generated nothing.

**Comment by jaysuk** [comment]
If you've not turned them on yet and already done the calibrations you'll
be fine.
Just make sure there's no config-override.g in sys. You can safely delete
it and it'll be regenerated

**Comment by MKHTexas** [comment]
Where will that config-override.g be? Is it a file or a line in a file?

**Comment by jaysuk** [comment]
It would be a file in the sys folder on your SD card (not in the GitHub
repo). If it doesn't exist that's fine
